### ISSUE TITLE
Add pre-commit hook, pull request template and a Dockerfile

### ISSUE THREAD

**Issue by Coinhexa** [fpgmaas/cookiecutter-poetry#39]
https://pre-commit.com/

**Comment by Coinhexa** [comment]
Sample .pre-commit-config.yaml
```

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
-   repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake -r -i --remove-all-unused-imports --remove-unused-variables
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py37-plus
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
      - id: kacl-verify
        name: kacl-verify
        entry: poetry run kacl-cli verify
        language: system
        files: 'CHANGELOG.md'
        pass_filenames: false

```
